version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-wallet-app
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    restart: always
    networks:
      - go-wallet-network

  postgres:
    image: postgres:13
    container_name: postgresdb
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - go-wallet-network

networks:
  go-wallet-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
